### ISSUE TITLE
Melhoria em Navegação das páginas

### ISSUE THREAD

**Issue by matheuscamarques** [rubensdemelo/flutter-para-iniciantes#20]
Adicionar próximo , e anterior nos tópicos no fim de cada página.

- [ ]  [Sobre este livro](README.md)
- [ ]   [Como o ebook está organizado?](como-o-livro-esta-organizado.md)
- [ ]   [O que é Flutter?](o-que-e-flutter.md)
- [ ]   [Por que o Flutter?](por-que-o-flutter.md)
- [ ]   [Este ebook é para mim?](quem-deve-ler.md)
- [ ]   [Dart: Não tenha medo](dart-nao-tenha-medo.md)
- [ ]   [Developer Experience](developer-experience.md)
- [ ]  [Visão Geral](visao-geral.md)
- [ ]  [Arquitetura](arquitetura.md)
- [ ]  [Instalação e configuração do ambiente](instalacao-e-configuracao-do-ambiente.md)
- [ ]  [Hello World](hello-world.md)
- [ ]  [Anatomia de um aplicativo](basico/anatomia-de-um-aplicativo.md)
- [ ]  [Widgets](basico/widgets.md)
- [ ]  [Stateless x Stateful](basico/stateless-stateful.md)
- [ ]  [Ciclo de vida dos widgets](basico/ciclo-de-vida.md)
- [ ]  [Navegação](basico/navegacao.md)
- [ ]  [Layout](widgets/layout.md)
- [ ]  [Material](widgets/material.md)
- [ ]  [Cupertino](widgets/cupertino.md)
- [ ]  [Widget Tree](gerenciamento-de-estado/widget-tree.md)
- [ ]  [Estado: Local e Global](gerenciamento-de-estado/estado-local-e-global.md)
- [ ]  [setState\(\)](gerenciamento-de-estado/setstate.md)
- [ ]  [InheritedWidget](gerenciamento-de-estado/inheritedwidget.md)
- [ ]  [scoped\_model](gerenciamento-de-estado/scoped_model.md)
- [ ]  [BLoC](gerenciamento-de-estado/bloc.md)
- [ ]  [Introdução](animacoes/introducao.md)
- [ ]  [Implícitas](animacoes/implicitas.md)
- [ ]  [Rock In Rio](aplicativo-1-rock-in-rio/rock-in-rio.md)
- [ ]  [O backend do seu aplicativo](firebase/firebase.md)
- [ ]  [O framework da Amazon](aws-amplify/o-framework-da-amazon.md)
- [ ]  [Copia e Cola](copia-e-cola/so.md)

**Comment by rubensdemelo** [comment]
a nova versao do gitbook já disponibiliza esta funcionalidade
