### ISSUE TITLE
Criar um Projeto de Plataforma Editor de Conteúdo do Livro

### ISSUE THREAD

**Issue by matheuscamarques** [rubensdemelo/flutter-para-iniciantes#21]
A ideia desse projeto é criar um projeto web , para que seja mais fácil editar os conteúdos desse livro
a minha ideia é montar um tutorial de como construir essa feature. 

Levantamentos de requisitos : 
- Backend Dart - O backend vai ter a função de ler todas as arvores de arquivos , editar , remover e alterar esses arquivos e pastas.
- Front End Flutter Web - O front end deve facilitar a edição das páginas é interessante ter um input de texto como a do github.

**Comment by rubensdemelo** [comment]
@matheuscamarques Mateus, o próprio gitbook.com já oferece toda a estrutura para editar o conteúdo. Utilizando os arquivos .md como fonte de conteúdo e também fornecendo uma interface intuitiva para a edição.
